import '@radix-ui/themes/styles.css';
import './theme-config.css';
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Container, Theme, ThemePanel} from '@radix-ui/themes';
import NavBar from "@/app/NavBar";
import AuthProvider from "@/app/auth/Provider";
import QueryClientProvider from "@/app/QueryClientProvider";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
      <html lang="en">
      <body className={`${inter.variable}`}>
      <QueryClientProvider>
        <AuthProvider>
        <Theme appearance="dark" grayColor="slate" radius="large">
          <NavBar/>
          <main className="p-5">
            <Container>{children}</Container>
          </main>
          {/*<ThemePanel/>*/}
        </Theme>
      </AuthProvider>
      </QueryClientProvider>
      </body>
      </html>
  )
}
